name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x, 23.x]
    steps:
    - uses: actions/checkout@v4
    - run: corepack enable
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: pnpm install --frozen-lockfile
    - run: pnpm build
    - run: pnpm test
    - run: pnpm dlx @arethetypeswrong/cli . --pack
